QT.Kirigami2.VERSION = 5.76.0
QT.Kirigami2.MAJOR_VERSION = 5
QT.Kirigami2.MINOR_VERSION = 76
QT.Kirigami2.PATCH_VERSION = 0
QT.Kirigami2.name = KF5Kirigami2
QT.Kirigami2.module = KF5Kirigami2
QT.Kirigami2.defines = 
QT.Kirigami2.includes = $$PWD/../../include/Kirigami2
QT.Kirigami2.private_includes =
QT.Kirigami2.libs = $$PWD/../../lib
QT.Kirigami2.depends = core qml quick svg
QT.Kirigami2.module_config = 
